Repository runtimeverification/llvm-backend, pull requests merged in 2023-04, with the labels that each got.

#722 Implement block to AST using parser
  bindings/c/include/kllvm-c/kllvm-c.h
  bindings/c/lib.cpp
  bindings/python/package/kllvm/__init__.py
  bindings/python/runtime.cpp
  include/runtime/header.h
  lib/parser/KOREParser.cpp
  runtime/util/ConfigurationPrinter.cpp
  test/c/Inputs/api.c
  test/c/Inputs/api.h
  test/c/Inputs/fd_leak.c
  test/c/Inputs/fd_leak_init.kore
  test/c/Inputs/reify.c
  test/c/refs/test_reify.ref
  test/c/test_fd_leak.kore
  test/c/test_reify.kore
  test/python/test_steps.py
Labels: automerge

#727 Switch to new GH Runner based deps updater
  .github/workflows/release.yml
Labels: automerge

#733 Migrate uses of deprecated APIs
  include/kllvm/codegen/Debug.h
  lib/codegen/CreateTerm.cpp
  lib/codegen/Debug.cpp
  lib/codegen/EmitConfigParser.cpp
Labels: automerge

#735 Update llvm-kompile-testing usage
  bin/llvm-kompile-testing
Labels: automerge, documentation

#737 Add handling of \u and \U unicode escape sequences
  include/kllvm/parser/KOREScanner.h
  lib/parser/KOREScanner.l
  test/defn/test-unicode.kore
  test/input/test-unicode.in
  test/output/test-unicode.out.diff
Labels: bug, automerge

#739 Add missing structural features to AST module
  bindings/python/ast.cpp
  include/kllvm/ast/AST.h
  test/python/test_patterns.py
  test/python/test_sorts.py
  test/python/test_symbols.py
Labels: automerge

#744 Enforce UTF-8 for decision tree YAML
  lib/codegen/CMakeLists.txt
  lib/codegen/DecisionParser.cpp
  matching/src/main/scala/org/kframework/backend/llvm/matching/dt/DecisionTree.scala
Labels: automerge

#741 Fix `side_function` on K Match on GDB
  debug/kgdb.py
  include/runtime/header.h
  runtime/CMakeLists.txt
  runtime/collections/CMakeLists.txt
  runtime/collections/kelemle.cpp
  runtime/equality.ll
Labels: bug, automerge

#751 Add missing case to pattern matching for new-format rules
  matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
Labels: automerge
