Repository runtimeverification/llvm-backend, pull requests merged in 2023-03, with the labels that each got.

#675 Fixing breaking nix update for cachix
  .github/workflows/test-flake.yml
  .github/workflows/update.yml
Labels: automerge

#671 Fix bug involving non-canonicalized MapP, ListP, or SetP
  matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/Pattern.scala
  matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/SortCategory.scala
  test/defn/kool-static.kore
  test/input/kool-static.in
  test/output/kool-static.out.diff
Labels: automerge

#679 Don't strip LLVM backend libraries
  nix/llvm-backend.nix
Labels: automerge

#680 Fix llvm build on Arch
  CMakeLists.txt
  tools/kore-arity/CMakeLists.txt
  tools/kore-convert/CMakeLists.txt
  tools/kore-strip/CMakeLists.txt
  tools/llvm-kompile-codegen/CMakeLists.txt
  unittests/compiler/CMakeLists.txt
Labels: automerge

#681 Clean up top-level CMake code
  CMakeLists.txt
  bin/CMakeLists.txt
  cmake/FindDependencies.cmake
  cmake/FindLLVM.cmake
  cmake/FixHomebrew.cmake
  cmake/KLLVMCompilerFlags.cmake
  cmake/RuntimeConfig.cmake
  deps/CMakeLists.txt
  include/CMakeLists.txt
  runtime/CMakeLists.txt
  tools/CMakeLists.txt
Labels: automerge

#682 Update INSTALL.md to add BUILD_TESTS option
  INSTALL.md
Labels: automerge, documentation

#678 Update `kprint` command line options implementation
  tools/kprint/main.cpp
Labels: enhancement, automerge

#685 Creating new test to `--search`
  test/input/search/search.initial.in
  test/input/search/search.next1.in
  test/lit.cfg.py
  test/output/search/search.initial.out.diff
  test/output/search/search.next1.out.diff
  test/search/search.kore
Labels: enhancement, automerge, devops

#684 Restructure initial LLDB support
  bin/llvm-kompile-clang
  cmake/FindLLVM.cmake
  debug/CMakeLists.txt
  debug/klldb.py
  lib/codegen/Debug.cpp
Labels: automerge

#686 add missing version to pom
  matching/pom.xml
  nix/llvm-backend-matching.mavenix.lock
Labels: automerge

#683 Write intro to backend documentation
  docs/README.md
  docs/binary-kore.md
  docs/developer-guide.md
  docs/images/compilation-dark.svg
  docs/images/compilation.svg
  docs/images/execution-dark.svg
  docs/images/execution.svg
  docs/technical-documentation.md
Labels: automerge

#688 Improve hiding of LLVM options
  tools/kore-arity/main.cpp
  tools/kore-convert/main.cpp
  tools/kore-strip/main.cpp
  tools/kprint/main.cpp
Labels: automerge

#689 Add support to `total` like `functional`
  lib/ast/AST.cpp
  matching/src/main/scala/org/kframework/backend/llvm/matching/Generator.scala
Labels: automerge

#674 Fix bug involving krun --search, map/set choice, and priority
  include/kllvm/codegen/Decision.h
  lib/codegen/Decision.cpp
  test/input/choice-priority-search.in
  test/output/choice-priority-search.out.diff
  test/search/choice-priority-search.kore
Labels: automerge

#697 Correct typo in binary docs
  docs/binary-kore.md
Labels: automerge

#699 Update flags definition and naming of `llvm-kompile-testing`
  bin/llvm-kompile-testing
Labels: enhancement, automerge

#703 Add support to `--binary-output` on search interpreter
  include/runtime/header.h
  runtime/main/search.cpp
  runtime/util/ConfigurationSerializer.cpp
  test/search/search.kore
Labels: enhancement, automerge

#704 Output processed KORE from `kprint`
  include/kllvm/printer/printer.h
  lib/printer/printer.cpp
  test/unparse/exp/exp2kore.cfg.kore
  test/unparse/exp/exp2kore.cfg.kore.out
  tools/kprint/main.cpp
Labels: automerge

#694 don't assign special priorities to cooling rules
  include/kllvm/codegen/Decision.h
  lib/codegen/Decision.cpp
  matching/src/main/scala/org/kframework/backend/llvm/matching/Matching.scala
  matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
  test/input/choice-priority-search.in
  test/output/choice-priority-search.out.diff
  test/search/choice-priority-search.kore
Labels: automerge

#696 Enforce C++17 in llvm-kompile-clang
  bin/llvm-kompile-clang
Labels: automerge

#698 Initial K LLDB support
  .github/workflows/test-flake.yml
  cmake/FindLLVM.cmake
  debug/CMakeLists.txt
  debug/k_lldb_path
  debug/klldb.py
  include/runtime/header.h
  nix/overlay.nix
  runtime/util/ConfigurationParser.cpp
  runtime/util/ConfigurationPrinter.cpp
Labels: automerge

#707 Write initial documentation for "backend as a library"
  docs/embedding.md
  docs/technical-documentation.md
Labels: automerge

#706 Duplicate dependabot PR #687
  matching/pom.xml
  nix/llvm-backend-matching.mavenix.lock
Labels: automerge

#711 Infer shared library extension in `c` mode
  bin/llvm-kompile-clang
Labels: automerge

#712 Call uname from Nix properly
  nix/llvm-backend.nix
Labels: automerge

#713 Fix quoting of shell regex
  bin/llvm-kompile-clang
  test/c/test_infer_ext.kore
Labels: automerge

#714 Implement KORE parser for C bindings
  bindings/c/include/kllvm-c/kllvm-c.h
  bindings/c/lib.cpp
  test/c/Inputs/parse.c
  test/c/test_parse.kore
Labels: automerge

#716 Improvements to C binding tests
  test/c/Inputs/api.c
  test/c/Inputs/api.h
  test/c/Inputs/binary_simplify.c
  test/c/Inputs/bool.c
  test/c/Inputs/bytes.c
  test/c/Inputs/k.c
  test/c/Inputs/kitem.c
  test/c/Inputs/parse.c
  test/c/Inputs/simplify.c
  test/c/Inputs/steps.c
  test/c/test_binary_simplify.kore
  test/c/test_bytes.kore
  test/c/test_c.kore
  test/c/test_k.kore
  test/c/test_kitem.kore
  test/c/test_parse.kore
  test/c/test_simplify.kore
  test/c/test_steps.kore
  test/lit.cfg.py
Labels: automerge

#717 Add flag to get backend include dir from `llvm-kompile`
  bin/llvm-kompile
  test/lit.cfg.py
Labels: automerge

#708 Introducing `k-rule-find` tool
  include/kllvm/codegen/Debug.h
  lib/codegen/Debug.cpp
  test/k-rule-find/definition.kore
  test/lit.cfg.py
  test/output/k-rule-find/rule-label.out.diff
  tools/CMakeLists.txt
  tools/k-rule-find/CMakeLists.txt
  tools/k-rule-find/main.cpp
Labels: automerge
