Repository runtimeverification/llvm-backend, pull requests merged in 2023-05, with the labels that each got.

#755 Revert "Revert "Introducing API to create temporary files""
  include/kllvm/util/temporary_file.h
  lib/parser/KOREParser.cpp
  runtime/io/logTerm.cpp
  runtime/io/parseKORE.cpp
  runtime/util/ConfigurationPrinter.cpp
  test/binary/test_61.kore
  test/input/test_61.in
  test/output/test_61.out.diff
  tools/kore-strip/main.cpp
Labels: enhancement, automerge

#760 Delete `Hyph` translation as it's not part of KORE Syntax anymore
  lib/ast/AST.cpp
Labels: automerge, code generation

#756 Introducing llvm backend support for `--execute-to-branch` feature
  runtime/main/search.cpp
  runtime/util/search.cpp
  test/input/search-execute-to-branch.in
  test/output/search-execute-to-branch.out.diff
  test/search/k-files/search-execute-to-branch.k
  test/search/search-execute-to-branch.kore
Labels: enhancement, automerge

#764 Desugar `\{left,right}-assoc`
  bindings/c/include/kllvm-c/kllvm-c.h
  bindings/c/lib.cpp
  bindings/python/ast.cpp
  include/kllvm/ast/AST.h
  lib/ast/AST.cpp
  test/c/Inputs/api.c
  test/c/Inputs/api.h
  test/c/Inputs/remove_assoc.c
  test/c/k-files/remove_assoc.k
  test/c/test_remove_assoc.kore
Labels: automerge

#763 Reorganizing `set -x` calls for verbose execution
  bin/llvm-krun
Labels: automerge

#767 Add missing recursion case
  lib/ast/AST.cpp
Labels: automerge

#772 Fix broken test mechanism
  test/lit.cfg.py
Labels: automerge

#774 Fix minor memory leaks
  bindings/c/lib.cpp
  test/c/Inputs/remove_assoc.c
Labels: automerge

#775 Improving `get_ui` error message
  runtime/strings/bytes.cpp
Labels: enhancement, automerge
