Repository runtimeverification/llvm-backend, pull requests merged in 2024-05, with the labels that each got.

#1040 Replace `LLVMREwriteEvent` with `llvm_rewrite_event`
  bindings/python/ast.cpp
  package/debian/changelog
  package/version
Labels: automerge, bindings

#1041 Fix usage of github PR SHA in release job
  .github/workflows/release.yml
  package/debian/changelog
  package/version
Labels: automerge

#1047 Fix `llvm-kompile pythonast`
  bin/llvm-kompile-clang
  test/python/test_pythonast.py
Labels: automerge

#1049 Update regex terminals to match new syntax
  test/defn/k-files/wasm.k
Labels: automerge

#1054 Adding `--` back to `llvm-kompile` call in `llvm-kompile-testing`
  bin/llvm-kompile-testing
Labels: automerge, debugger

#1029 Don't emit branch unnecessary check for injection
  include/kllvm/ast/AST.h
  lib/ast/definition.cpp
  lib/codegen/CreateTerm.cpp
Labels: automerge

#857 [Debugger] Introducing lldb on for `llvm-krun` script
  bin/llvm-krun
Labels: automerge, debugger

#1059 Using `map` instead of `unordered_map` to ensure reproducibility of kore definition generation
  include/kllvm/ast/attribute_set.h
Labels: bug, automerge

#1062 Update llvm-krun: removing `set -x`
  bin/llvm-krun
Labels: automerge

#1053 Introducing `Ordinal` KORE Attribute
  bindings/python/ast.cpp
  include/kllvm/ast/AST.h
  include/kllvm/ast/attribute_set.h
  include/kllvm/codegen/ProofEvent.h
  lib/ast/attribute_set.cpp
  lib/ast/definition.cpp
  lib/codegen/Decision.cpp
  lib/codegen/ProofEvent.cpp
  test/python/test_proof_trace.py
  test/python/test_proof_trace_slow.py
Labels: automerge

#1056 Introducing llvm-kompile `compute-ordinal` and `compute-loc` tools
  bin/llvm-kompile-compute-loc
  bin/llvm-kompile-compute-ordinal
  include/kllvm/ast/util.h
  lib/ast/CMakeLists.txt
  lib/ast/util.cpp
  test/defn/compute-ordinal-loc/definition.kore
  test/defn/compute-ordinal-loc/k-files/inc.k
  test/defn/compute-ordinal-loc/line_number_rule
  test/lit.cfg.py
  tools/CMakeLists.txt
  tools/llvm-kompile-compute-loc/CMakeLists.txt
  tools/llvm-kompile-compute-loc/main.cpp
  tools/llvm-kompile-compute-ordinal/CMakeLists.txt
  tools/llvm-kompile-compute-ordinal/main.cpp
Labels: automerge

#1066 Drop intel macOS support in CI
  .github/workflows/test.yml
Labels: automerge

#1067 Don't invoke Maven every time we run a test
  bin/llvm-kompile-testing
  nix/overlay.nix
Labels: automerge

#1070 Update to new Nixpkgs version
  flake.lock
  nix/llvm-backend.nix
  nix/overlay.nix
Labels: automerge

#1065 Refactor proof hint parser
  include/kllvm/binary/ProofTraceParser.h
  include/kllvm/binary/deserializer.h
  lib/binary/ProofTraceParser.cpp
  lib/binary/deserializer.cpp
  test/lit.cfg.py
Labels: automerge

#1068 Apply backwards-compatible changes for LLVM 18
  cmake/FindLLVM.cmake
  deps/CMakeLists.txt
  include/kllvm/codegen/Util.h
  lib/binary/CMakeLists.txt
  lib/codegen/ApplyPasses.cpp
  lib/codegen/CMakeLists.txt
  lib/codegen/CreateStaticTerm.cpp
  lib/codegen/CreateTerm.cpp
  lib/codegen/Decision.cpp
  lib/codegen/EmitConfigParser.cpp
  lib/codegen/ProofEvent.cpp
  lib/codegen/Util.cpp
  runtime/strings/strings.cpp
Labels: automerge

#1071 Update CI matrix for LLVM 18
  flake.nix
Labels: automerge

#1074 Adding `llvm:cl::opt` support to `kore-rich-header`
  tools/kore-rich-header/main.cpp
Labels: automerge
