Repository runtimeverification/llvm-backend, pull requests merged in 2024-06, with the labels that each got.

#1073 Improving Proof Trace Documentation
  docs/proof-trace.md
Labels: automerge

#1075 Add python bindings for proof hint streaming parser
  bindings/python/ast.cpp
  include/kllvm/binary/ProofTraceParser.h
  include/kllvm/binary/deserializer.h
  lib/binary/ProofTraceParser.cpp
  test/python/test_proof_trace.py
  tools/kore-proof-trace/main.cpp
Labels: automerge

#1084 Disable LTO when building Debian packages
  package/debian/rules.jammy
  package/debian/rules.noble
Labels: automerge

#1079 Update `proof-trace.md` with new changes
  docs/proof-trace.md
Labels: automerge, documentation

#1083 simplify gc code for alwaysgc roots
  include/runtime/collect.h
  lib/codegen/Decision.cpp
  runtime/collect/collect.cpp
Labels: automerge

#1085 Fix typo in release workflow
  .github/workflows/release.yml
Labels: automerge

#1082 add flag to control whether gc should be enabled or not
  include/kllvm/codegen/CreateTerm.h
  include/runtime/header.h
  lib/codegen/CreateTerm.cpp
  runtime/alloc/alloc.cpp
  runtime/alloc/arena.cpp
  runtime/util/ConfigurationParser.cpp
  unittests/runtime-collections/lists.cpp
Labels: automerge

#1080 Add MapIter and SetIter sort categories
  bindings/python/ast.cpp
  cmake/RuntimeConfig.cmake
  config/macros.h
  include/kllvm/ast/AST.h
  lib/ast/AST.cpp
  lib/codegen/CreateStaticTerm.cpp
  lib/codegen/CreateTerm.cpp
  lib/codegen/Debug.cpp
  lib/codegen/Decision.cpp
  lib/codegen/EmitConfigParser.cpp
Labels: automerge

#1087 set noreturn attribute on finish-rewriting call site
  lib/codegen/Decision.cpp
Labels: automerge

#1088 create conditional compilation flag for stack maps
  cmake/KLLVMCompilerFlags.cmake
  config/macros.h
Labels: automerge

#1090 Update name of `EventType` and expose `__repr__` from `llvm_rewrite_trace_iterator`
  bindings/python/ast.cpp
  test/python/test_proof_trace.py
Labels: automerge, bindings

#1081 add libunwind as dependency
  .github/workflows/Dockerfile
  Dockerfile.arch
  INSTALL.md
  bin/llvm-kompile-clang
  nix/llvm-backend.nix
  nix/overlay.nix
  package/debian/control.jammy
  package/debian/control.noble
Labels: automerge

#1089 add kore_clear function that clears alwaysgcspace on every step
  include/kllvm/codegen/Util.h
  include/runtime/alloc.h
  lib/codegen/Decision.cpp
  lib/codegen/Util.cpp
  runtime/alloc/alloc.cpp
  runtime/collect/collect.cpp
Labels: automerge

#1091 Move simple CI jobs to latest Ubuntu version
  .github/workflows/clang-format-check.yml
  .github/workflows/test.yml
Labels: automerge
